CREATE DATABASE MAFIOSILLOS
GO
USE MAFIOSILLOS
GO
--EJERCICIO 1--
--VEASE FOLIOS DEL EXAMEN--

--EJERCICIO 2--

CREATE TABLE DONES (
ID_DON CHAR(9)
, NOMBRE NVARCHAR(30)
, APELLIDOS NVARCHAR (40)
, APODO NVARCHAR (25)
, FECHA_NACIMIENTO_DON DATE
, PROCEDENCIA NVARCHAR(30)
, FECHA_DE_NOMBRAMIENTO DATE
, CONSTRAINT PK_ID_DON PRIMARY KEY (ID_DON)
)
GO

CREATE TABLE CONSIGLIERES (
APODO NVARCHAR(25)
, NOMBRE NVARCHAR (30)
, APELLIDOS NVARCHAR (40)
, FECHA_NACIMIENTO_CONSIGLIERE DATE
, PROCEDENCIA NVARCHAR(30)
, TITULACION NVARCHAR (50)
, ID_DON SMALLINT
, CONSTRAINT PK_APODO PRIMARY KEY (APODO)
, CONSTRAINT FK_ID_DON FOREIGN KEY (ID_DON) REFERENCES DONES (ID_DON) ON DELETE NO ACTION ON UPDATE CASCADE
)
GO

CREATE TABLE CONTROLA (
NOMBRE_FAMILIA NVARCHAR (25)
, ID_TERRITORIO SMALLINT
, ID_NEGOCIO SMALLINT
, CONSTRAINT PK_CLAVE_PRIMARIA_CONTROLA PRIMARY KEY (NOMBRE_FAMILIA, ID_TERRITORIO, ID_NEGOCIO)
)
GO

CREATE TABLE TERRITORIOS (
ID_TERRITORIO CHAR(4)
, CIUDAD NVARCHAR (30)
, BARRIO NVARCHAR (30)
, CONSTRAINT PK_ID_TERRITORIO PRIMARY KEY (ID_TERRITORIO)
)
GO

CREATE TABLE NEGOCIOS (
ID_NEGOCIO CHAR(5)
, DENOMINACION NVARCHAR (20)
, LEGALSN BIT
, CONSTRAINT PK_ID_NEGOCIO PRIMARY KEY (ID_NEGOCIO)
)
GO

CREATE TABLE FAMIGLIAS (
NOMBRE_FAMILIA NVARCHAR (30)
, ID_DON CHAR(9)
, PROCEDENCIA NVARCHAR(30)
, FAMILIA_PROTEGIDA NVARCHAR (30)
, CONSTRAINT PK_NOMBRE_FAMILIA PRIMARY KEY (NOMBRE_FAMILIA)
, CONSTRAINT FK_ID_DON FOREIGN KEY (ID_DON) REFERENCES DONES(ID_DON) ON DELETE NO ACTION ON UPDATE CASCADE
)
GO

CREATE TABLE CAPOS (
ID_CAPO CHAR(9)
, NOMBRE NVARCHAR(25)
, APELLIDOS NVARCHAR (35)
, APODO NVARCHAR (25)
, FECHA_NACIMIENTO_CAPO DATE
, PROCEDENCIA NVARCHAR(30)
, NOMBRE_FAMILIA NVARCHAR(30)
, CONSTRAINT PK_ID_CAPO PRIMARY KEY (ID_CAPO)
, CONSTRAINT UC_ID_CAPO UNIQUE (ID_CAPO)
, CONSTRAINT FK_NOMBRE_FAMILIA FOREIGN KEY (NOMBRE_FAMILIA) REFERENCES FAMIGLIAS(NOMBRE_FAMILIA) ON DELETE NO ACTION ON UPDATE CASCADE
)
GO

CREATE TABLE LUGARTENIENTES (
ID_CAPO CHAR(9)
, ID_LUGARTENIENTE CHAR(9)
, NOMBRE NVARCHAR(25)
, APELLIDOS NVARCHAR (35)
, APODO NVARCHAR (25)
, CONSTRAINT FK_ID_CAPO FOREIGN KEY (ID_CAPO) REFERENCES CAPOS(ID_CAPO) ON DELETE NO ACTION ON UPDATE CASCADE
, CONSTRAINT PK_ID_LUGARTENIENTE PRIMARY KEY (ID_LUGARTENIENTE)
)
GO

CREATE TABLE TECNICAS_DE_PERSUASION (
ID_TECNICA_DE_PERSUASION SMALLINT IDENTITY(1,1)
, DENOMINACION NVARCHAR (20)
, CONSTRAINT PK_TECNICA_DE_PERSUASION PRIMARY KEY (ID_TECNICA_DE_PERSUASION)
)
GO

CREATE TABLE CAPOS_TECNICAS_DE_PERSUASION (
ID_CAPO CHAR(9)
, ID_TECNICA_DE_PERSUASION SMALLINT IDENTITY(1,1)
, CONSTRAINT PK_ID_CAPO_ID_TECNICA_DE_PERSUASION PRIMARY KEY (ID_CAPO, ID_TECNICA_DE_PERSUASION)
, CONSTRAINT FK_ID_CAPO FOREIGN KEY (ID_CAPO) REFERENCES CAPOS(ID_CAPO) ON DELETE NO ACTION ON UPDATE CASCADE
, CONSTRAINT FK_ID_TECNICA_DE_PERSUASION FOREIGN KEY (ID_TECNICA_DE_PERSUASION) REFERENCES TECNICAS_DE_PERSUASION(ID_TECNICA_DE_PERSUASION) ON DELETE NO ACTION ON UPDATE CASCADE
)
GO

CREATE TABLE SOLDATOS (
ID_SOLDATO CHAR(10)
, NOMBRE_SOLDATO NVARCHAR (25)
, APELLIDOS_SOLDATO NVARCHAR (50)
, APODO_SOLDATO NVARCHAR (25)
, FECHA_NACIMIENTO_SOLDATO DATE
, PROCEDENCIA_SOLDATO NVARCHAR(30)
, TATUAJE_PRINCIPAL NVARCHAR (25)
, ID_CAPO CHAR(9)
, CONSTRAINT PK_ID_SOLDATO PRIMARY KEY (ID_SOLDATO)
, CONSTRAINT FK_ID_CAPO FOREIGN KEY (ID_CAPO) REFERENCES CAPOS(ID_CAPO)
)
GO

CREATE TABLE ARMAS (
ID_ARMA CHAR (9)
, CONSTRAINT PK_ID_ARMA PRIMARY KEY (ID_ARMA)
)
GO

CREATE TABLE SOLDATO_ARMA (
DESTREZA NVARCHAR (25)
,ID_SOLDATO CHAR(10)
,ID_ARMA CHAR(9)
, CONSTRAINT FK_ID_SOLDATO FOREIGN KEY (ID_SOLDATO) REFERENCES SOLDATOS (ID_SOLDATO)
, CONSTRAINT FK_ID_ARMA FOREIGN KEY (ID_ARMA) REFERENCES ARMAS (ID_ARMA)
, CONSTRAINT PK_SOLDATO_ARMA PRIMARY KEY(ID_SOLDATO,ID_ARMA)
)
GO
--EJERCICIO 3--

--EJERCICIO 4--

CREATE TABLE DELITOS (
ID_DELITOS CHAR(8)
, DENOMINACION NVARCHAR (35)
, ARTICULOCP DECIMAL(4,1)
, CONDENAMIN SMALLINT
, CONDENAMAX SMALLINT
, CONSTRAINT PK_ID_DELITOS PRIMARY KEY (ID_DELITOS)
, CONSTRAINT CK_CONDENAMAX CHECK(CONDENAMAX LIKE '[CONDENAMIN - 360]')
)
GO
--EJERCICIO 5--
CREATE TABLE SOLDATO_DELITO (

)
GO
CREATE TABLE CAPO_DELITO (

)
GO